src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Warehouse</fullName>
        <active>true</active>
        <description>A warehouse is a location where Book warehouse Solutions stores inventory.</description>
        <label>Warehouse</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Book_Order__c.object
<CustomObject>
    <description>A simplified order object used by Book Warehouse Solutions</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The Contact that this order belongs to.</description>
        <inlineHelpText>The Contact that this order belongs to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Book Order</label>
    <nameField>
        <label>Book Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User that this Contact is related to.</description>
        <inlineHelpText>The User that this Contact is related to.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Account field on a Product indicates the Account that offers this product to its customers.</description>
        <inlineHelpText>The Account field on a Product indicates the Account that offers this product to its customers.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <description>Book Warehouse Solutions does not use the standard Pricebook2 object in their solution.  Instead, the current price for a Book or Collection is stored on the Product2 (Book) object itself.</description>
        <inlineHelpText>The current price for a Book or Collection.</inlineHelpText>
        <label>Current Price</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <description>This is the quantity of this particular product in inventory.</description>
        <inlineHelpText>This is the quantity of this particular product in inventory.</inlineHelpText>
        <label>Inventory</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/TestDataHelper.cls
/*==============================================
* Apex Class Name : BookList
* Version             : 1.0 
* Created Date        : 10 October 2016
* Function            : If Credit Collection Queue has more than 4 records, then send email notification queue members.
* Modification Log 
* Developer                   Date                    Description
* -----------------------------------------------------------------------------------------------------------
* Krishna Bogavelli           10/Oct/2016            Initial version
-------------------------------------------------------------------------------------------------------------
=================================================*/
@isTest
public class TestDataHelper {
 
    Public Static List<account> createWhareHouseAccts(){ 
        id WhareRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Warehouse').getRecordTypeId(); 
        List<Account> WhareHouseAcct = new List<Account>();
        //created 24 Book wharehouse Accounts
        for (Integer i=0; i<24; i++){ 
            WhareHouseAcct.add(new Account(Name = 'Warehouse'+i,RecordTypeId =WhareRecTypeId, Type= 'Warehouse'));
        }
        Insert WhareHouseAcct;
        List<Account> returnAcctRecs = [select id,Name,RecordTypeId,Type from Account];
        return returnAcctRecs;
    }
 //===================================================================================================================================//   
    Public Static List<account> createbookSellerAccts(){ 
        id BookSellRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Book Seller').getRecordTypeId(); 
        List<Account> bookSellerAcct = new List<Account>();
        //created  202 Book Seller Accounts 
        for (Integer i=0; i<202; i++){  
            bookSellerAcct.add(new Account(Name = 'Book Seller Store'+i,RecordTypeId =BookSellRecTypeId, Type= 'Book Seller'  ));
        }
        Insert bookSellerAcct; 
        
        List<Account> returnAcctRecs = [select id,Name,RecordTypeId,Type from Account];
     return returnAcctRecs;
    }
     
//====================================================================================================================================//
    Public Static List<product2> CreateBooks(){
        createbookSellerAccts(); createWhareHouseAccts();
        
        List<Account> getBookSellerAcct = new List<Account>(createbookSellerAccts());// [select id from account where type ='Book Seller'];
        List<Account> getWhareHouseAcct = new List<Account>(createWhareHouseAccts());//[select id from account where type ='Warehouse'];
    
        List<Product2> BookSellerBooks = new List<Product2>();
        List<Product2> WhareHouseBooks = new List<Product2>();
    
        Integer count = 0;
        for (Integer i=0;i<300;i++){
            //Inventory Record
            system.assertNotEquals(getWhareHouseAcct[2].Id,Null);
             WhareHouseBooks.add(new Product2(name = 'Book_'+i,Family = 'Inventory',IsActive=True,Inventory__c = 100,Account__c = getWhareHouseAcct[2].Id ));
            if(i<30){system.assertNotEquals(getWhareHouseAcct[0].Id,Null);
               WhareHouseBooks.add(new Product2(name = 'Book_'+i,Family = 'Inventory',IsActive=True,Inventory__c = 100,Account__c = getWhareHouseAcct[0].Id ));		
            } else {
                 WhareHouseBooks.add(new Product2(name = 'Book_'+i,Family = 'Inventory',IsActive=True,Inventory__c = 100,Account__c = getWhareHouseAcct[1].Id ));
            }
    
            
            //Collection Records
            if(i==0){
              BookSellerBooks.add(new Product2(name = 'Book_'+i,Family = 'Collection',IsActive=True,Current_Price__c = 20,Account__c = getBookSellerAcct[0].Id));	
            }
            //Paperback Records
            if(i>0 && i<40){
              if(i <30){
                 BookSellerBooks.add(new Product2(name = 'Book_'+i,Family = 'Paperback',IsActive=True,Current_Price__c = 20,Account__c = getBookSellerAcct[0].Id ));		
              }else{
                 BookSellerBooks.add(new Product2(name = 'Book_'+i,Family = 'Paperback',IsActive=True,Current_Price__c = 20,Account__c = getBookSellerAcct[1].Id ));		
              }  
            }
            //Hardcover Records
            if(i>=40 ){
                if(i>=60){
                    BookSellerBooks.add(new Product2(name = 'Book_'+i,Family = 'Hardcover',IsActive=True,Current_Price__c = 20,Account__c = getBookSellerAcct[1].Id ));	
                }else {
                    BookSellerBooks.add(new Product2(name = 'Book_'+i,Family = 'Hardcover',IsActive=True,Current_Price__c = 20,Account__c = getBookSellerAcct[0].Id ));	
                }
            }
                      
           
        }
        Insert BookSellerBooks; 
        Insert WhareHouseBooks;
            
        List<Product2> returnCreatedBooks = [Select id, Name, Family,IsActive,Current_Price__c,Account__c FROM Product2];
    return returnCreatedBooks;
    }
//========================================================================================================================================//
    Public Static List<Contact> createContacts(Integer numOfContacts, String userName){
        List<Account> getBookSellerAcct = new List<Account>(createbookSellerAccts());
        user userinfo = [select id from user where name =: userName]; /*'BWS Customer'*/
        List<Contact> lstCont = new List<Contact>();
        for (Integer i=0;i<numOfContacts;i++){ 
            lstCont.add(new Contact(LastName = 'TestOrderUser'+i, User__c = userinfo.id, AccountId = getBookSellerAcct[i].id ));
        }
        Insert lstCont;
        List<Contact> returnCreatedContactRecs = [select id,Name,User__c,AccountId from contact];
    return returnCreatedContactRecs;
    }
//========================================================================================================================================//
    Public Static Contact createContact(id accountID,id userNameID){
  
        user userinfo = [select id from user where name ='BWS Customer'];
         Contact  createContact =  new Contact(LastName = 'TestOrderUser', User__c = userinfo.id, AccountId = accountID );
  
        Insert createContact;
        Contact returnCreatedContactRecs = [select id,Name,User__c,AccountId from contact Limit 1];
    return returnCreatedContactRecs;
    }

//========================================================================================================================================//
    Public static Book_Order__c bookOrder(id contactID){ 
        
        Book_Order__c createBookOrder = new Book_Order__c(Name = 'order_2',Contact__c  = contactID);
        Insert createBookOrder;
        Book_Order__c returnBookOrder = [SELECT id,name,Contact__c,Contact__r.Accountid From Book_Order__c Limit 1];
        return returnBookOrder;
    }
    
    
}